detectors:
  IrresponsibleModule:
    enabled: false

  FeatureEnvy:
    exclude:
      - Truemail::RSpec::ConfigurationHelper#create_configuration
      - Truemail::RSpec::ValidatorHelper#request_instance
      - Truemail::RSpec::AuditorHelper#create_auditor

  ControlParameter:
    exclude:
      - Truemail::RSpec::AuditorHelper#create_auditor
      - Truemail::RSpec::ValidatorHelper#create_servers_list

  NestedIterators:
    exclude:
      - Truemail::RSpec::ConfigurationHelper#configuration_block

  BooleanParameter:
    exclude:
      - Truemail::RSpec::ValidatorHelper#create_validator
      - Truemail::RSpec::AuditorHelper#create_auditor

  DuplicateMethodCall:
    exclude:
      - Truemail::RSpec::ValidatorHelper#mx_layer
      - Truemail::RSpec::ValidatorHelper#smtp_layer
      - Truemail::RSpec::ValidatorHelper#unstub_validation_layers

  LongParameterList:
    enabled: false

  TooManyStatements:
    enabled: false
