require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  TargetRubyVersion:  2.5
  NewCops: enable

# Metrics ---------------------------------------------------------------------

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

# Naming ----------------------------------------------------------------------

Naming/VariableNumber:
  Enabled: false

# Style -----------------------------------------------------------------------

Style/Documentation:
  Enabled: false

# Layout ----------------------------------------------------------------------

Layout/LineLength:
  Max: 140

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods

Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Gemspec ---------------------------------------------------------------------

Gemspec/RequireMFA:
  Enabled: false

# RSpec -----------------------------------------------------------------------

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
